#!/bin/bash
# expects variables to be set:
# - OSSRH_JIRA_USERNAME
# - OSSRH_JIRA_PASSWORD
# - GPG_KEY_NAME
# - GPG_PASSPHRASE
# expects file to exist:
# - .travis/gpg.asc

set -e

# Check the variables are set
if [ -z "$OSSRH_JIRA_USERNAME" ]; then
  echo "missing environment value: OSSRH_JIRA_USERNAME" >&2
  exit 1
fi

if [ -z "$OSSRH_JIRA_PASSWORD" ]; then
  echo "missing environment value: OSSRH_JIRA_PASSWORD" >&2
  exit 1
fi

if [ -z "$GPG_KEY_NAME" ]; then
  echo "missing environment value: GPG_KEY_NAME" >&2
  exit 1
fi

if [ -z "$GPG_PASSPHRASE" ]; then
  echo "missing environment value: GPG_PASSPHRASE" >&2
  exit 1
fi

# Prepare the local keyring (requires travis to have decrypted the file
# beforehand)
gpg --fast-import .travis/gpg.asc

# Run the maven deploy steps
mvn deploy -P publish -DskipTests=true --settings "${TRAVIS_BUILD_DIR}/.travis/mvn-settings.xml"
