
include $(GOROOT)/src/Make.inc

all: install

TARG=thriftlib/hank

DIRS=\
  PartitionServer\
  SmartClient\

GOFILES=\
  ttypes.go\
  PartitionServer.go\
  SmartClient.go\


include $(GOROOT)/src/Make.pkg

